name: Lint and test

on:
  push:

jobs:
  lint-build-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src
    steps:
      - uses: actions/checkout@v3

      - name: install dependencies
        run: sudo apt-get install check lcov clang-format valgrind cppcheck -y

      - name: lint
        run: make lint

      - name: build is ok
        run: make

      - name: test
        run: make test

      - name: check memory leaks
        run: |
          make clean
          make valgrind_tests

      - name: gcov coverage report
        run: make coverage_report

      - name: upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: try to gen gcov_report
        run: make gcov_report
